### ISSUE TITLE
Android Custom Views - Part 1(Extending View class)

### ISSUE THREAD

**Issue by kayere** [section-io/engineering-education#463]
### Brief Summary: 
 Android platform has a rich variety of views. These views tend to satisfy most applications' needs. However, developers sometimes need to create their own views in order to make their application's UI unique. There are two approaches to making custom views. This article is going to cover the first approach which is 'by extending the View class'.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Understand how to create custom views by extending the view class.
2. Know some use cases of custom views.
3. Know how to implement methods associated with the View class. 
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
@kayere We'd prefer that this be combined with Part 2 (suggested in #464 ). This article would have more value with the approach of 'When to Use Extending View Class vs Subclass with Android Custom Views'. I'm going to close the other issue, with the note that it be consolidated under this one.

**Comment by kayere** [comment]
Hello @ninjaginja, I am currently writing this article but I have a concern. Combining the two approaches in the same article makes it very long and might be boring to the reader. This is because each approach is a tutorial. I have read several articles online and all of them demonstrate each approach separately. I was asking if you could please consider allowing me to split the article. 
Regards.

**Comment by ninjaginja** [comment]
@kayere I'd argue that length does not necessarily correlate to interest level. In other words, just because an article is longer doesn't mean that it might be boring. Ultimately, I'll leave it up to you to determine the best way to structure the content, and if you feel that each can standalone without dependency on the other (and without repetition), then go ahead and make it two articles. Please note that further suggestions may arise in the review process.
