### ISSUE TITLE
Validating XML using DTD

### ISSUE THREAD

**Issue by srishilesh** [section-io/engineering-education#503]
### Brief Summary: 
In this article, a brief introduction about XML, the need of XML and its validation will be covered in detail, along with a sample implementation of its validation using DTD (Document Type Definition). 

### Key Takeaways: 
- The reader will be able to understand what are data serialization techniques
- The reader will get an overview on XML 
- The reader will understand the need of XML validation
- The reader will implement validation using DTD 

### References: 
- https://www.w3.org

**Comment by ninjaginja** [comment]
@srishilesh we prefer that you take a specific angle or practitioner's approach to content (such as with the other two article topics that you currently have open), rather than general overviews. I see that you crossed out the original title, which appears to be more inline with what we're looking for, i.e. "Validating XML using DTD"

**Comment by srishilesh** [comment]
> @srishilesh we prefer that you take a specific angle or practitioner's approach to content (such as with the other two article topics that you currently have open), rather than general overviews. I see that you crossed out the original title, which appears to be more inline with what we're looking for, i.e. "Validating XML using DTD"

Alright @ninjaginja , I will change the topic name to "Validating XML using DTD". (I was not sure, if topic name can be long, so crossed it out)
