### ISSUE TITLE
What Happens When JavaScript Runs My Code?

### ISSUE THREAD

**Issue by adrianmurage** [section-io/engineering-education#533]
### Brief Summary: 
An article that explains to the readers exactly what happens when they execute their JavaScript code

### Key Takeaways: 
An understanding of:
- Execution Contexts
- The Thread of Execution
- Variable Environments
- JS Call Stack

### References: 
Front End Masters
MDN Web Docs

**Comment by ninjaginja** [comment]
@adrianmurage I see that you've already opened a PR for this topic. In the future, please make sure that you submit your topic for approval before beginning on your article so that we can make sure no efforts are wasted if the topic doesn't align with our areas of interest. We'll go ahead and proceed with this one in the review queue. Thanks.

**Comment by adrianmurage** [comment]
@ninjaginja I apologize for this oversight.
I'll ensure to do that in future.
Thank you for your time and input.
