### ISSUE TITLE
Visual Studio Code vs. Atom: Which Text Editor is better for a Software Developer

### ISSUE THREAD

**Issue by JudyNduati** [section-io/engineering-education#554]
### Brief Summary: 
Every developer needs a good text editor. Let's take a look at VS Code vs. Atom and see what this two text editors have to offer.

### Key Takeaways: 
1. Visual Studio Code
2. Atom
3. VS Code vs. Atom: Similarities
4. VS Code vs. Atom: Differences
5. VS Code vs. Atom: Performance

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
https://forum.freecodecamp.org/t/is-atom-better-than-vscode/271011
https://www.infoworld.com/article/3405883/visual-studio-code-vs-atom-how-they-stack-up.html
https://careerkarma.com/blog/vscode-vs-atom/#:~:text=Atom%20becomes%20even%20more%20sluggish%20as%20you%20add%20extensions%20and%20plugins.&text=Visual%20Studio%20Code%2C%20however%2C%20is,for%20an%20overall%20faster%20experience.

**Comment by JudyNduati** [comment]
@hectorkambow How about this topic suggestion? I got no feedback

**Comment by hectorkambow** [comment]
@JudyNduati  Thank you Judy - I meant to follow up with you yesterday. 
Thinking through this topic suggestion. 
Although I like the suggestion (because I use Atom) I don't think this is exactly in the realms of EngEd content. 
It seems like it would be a very subjective topic - it seems like an opinion based preference. 

I'll check with the team - to see if there is a way to work it in. But in the meantime, I will say no on this one. ❌ 
Thank you. 
Lets try to suggest a different topic 👍

**Comment by JudyNduati** [comment]
Thank you for the insights, @hectorkambow. How about giving a review of the two softwares? I will give a topic suggestion based on functionality and rating.
