### ISSUE TITLE
How to create an API using Laravel

### ISSUE THREAD

**Issue by WanjaMIKE** [section-io/engineering-education#652]
### Brief Summary: 
Laravel is a PHP framework that make it easy for users to build high quality web applications. Laravel is preferred by many developers since it contains close to all required dependencies. It also eliminates a lot of boiler plate code. It is, therefore, easy to create APIs using this framework.

### Key Takeaways: 
 - Understand what APIs are
- Create a simple API using Laravel
- Debug errors that occur during compilation

### References: 
https://laravel.com/

**Comment by ninjaginja** [comment]
good topic @WanjaMIKE  - approved. 

I see that you've got several other topic suggestions in the queue as well. I'd like to advise that you work through previously suggested articles before suggesting new topics so that we can keep our pipeline clean and make sure that we're focusing on getting articles published.

**Comment by WanjaMIKE** [comment]
@ninjaginja Noted

**Comment by molly80** [comment]
@hectorkambow this is my article of another laravel issue please rectify. Thank you

**Comment by WanjaMIKE** [comment]
What article? Issue 714?

**Comment by WanjaMIKE** [comment]
@hectorkambow 
I am still working on this article

**Comment by hectorkambow** [comment]
> @hectorkambow
> I am still working on this article

Nothing to worry about - I had mistakenly linked this issue to another PR thinking that was the correct one 👍

**Comment by WanjaMIKE** [comment]
Okay, thank you
