### ISSUE TITLE
Build a Websockets Powered Tic-tac-toe with AdonisJS 

### ISSUE THREAD

**Issue by vicradon** [section-io/engineering-education#969]
### Brief Summary: 
Learn how web sockets work and how they are used in the real world by building Tic-tac-toe. Web sockets enable real-time communication in web applications. AdonisJS, a Node.js framework, has first-class support for web sockets. Tic-tac-toe is a simple I/O (Input/Output) application, so AdonisJS is a good fit for building it.

### Key Takeaways: 
1. How web sockets work
2. How cookies can be used to store socket ids
3. Best practices in designing socket-based applications

### References: 
1. https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
2. https://medium.com/@td0m/what-are-web-sockets-what-about-rest-apis-b9c15fd72aac

**Comment by ninjaginja** [comment]
good topic @vicradon - approved 👍 

One minor note, please be consistent with references to 'AdonisJs' and 'tic-tac-toe' (capitalized version only used at beginning of sentence 'Tic-tac-toe'). Also, you may consider incorporating web sockets into the title since that seems to be a key component of the tutuorial.

**Comment by vicradon** [comment]
Hi @ninjaginja 
Does the review process take more than 2 weeks?
